### ISSUE TITLE
Renaming the protocols from prot-YYYY--1 to prot-YYYY--001

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#100]
Here are the minor issues I wrote down after our discussions with the sweTerror project.

- [x] Have the same number of digits in the protocol files so they will show up in order. 
- [x] #408

**Comment by rbbby** [comment]
We should do this. But need to add the original KB filenames inside the xml files.

**Comment by BobBorges** [comment]
Maybe there's a reason to do this I don't see, but it seems like a time investment to create a map and re-link things all so the file list looks pretty in a GUI. pls close

**Comment by MansMeg** [comment]
I think this is not too hard to do with git. I think it came from @ninpnin originally?

**Comment by BobBorges** [comment]
@MansMeg this issue discussed this morning is still open

**Comment by MansMeg** [comment]
Great!

**Comment by MansMeg** [comment]
Ping @ljo

**Comment by ljo** [comment]
I still would like this to happen, since: 

- It is not only a GUI prettify listing thing, but also:
-  good file hygiene 
- inviting to more people when they see the files in expected order in alphabetically sorted lists without additional actions. 
-  Many processing tools that iterate over a directory fail to do the right numeric order this which then also requires extra processing for many tools (of many users) 
- I would even suggest the Riksdag aim for a change in of their naming conventions in the future as well 
- It can still be aligned to the original source document with an explicit document internal link (a structured metadata field) just like the `facs` attribute are actually referring to the actual page source

But like I said, I have not checked, if we have internal dependencies that will make things break or need larger rework that needs to be taken into consideration. Like @BobBorges mentioned in the meeting, there is a decision to be made, if it is wanted or not.

**Comment by BobBorges** [comment]
I agree with all your points! If I would name these files from the beginning, I'd definitely go with the leading 0 format, but I don't have any strong feelings now about changing it or not.

**Comment by MansMeg** [comment]
As I see it, there are "external" reasons to change the names. While the reasons not to change is more that it means slightly extra work for us. Then let's change.

I also think, long run, we should move all the PDFs to an open github library anyway so they also can be accessed and linked to for everyone. Then we could also change the original file names. 

What does @ninpnin thinks?

**Comment by ljo** [comment]
@MansMeg I certainly agree the PDFs should be moved and renamed as well. Also, if possible put the images of the pages which now, though documented, outside the auth requirement

**Comment by MansMeg** [comment]
Yes indeed. That is one of the main reasons. We have asked KB to open it up, but nothing has happened for years, so let's just move it to an open place. Ill open a separate issue for that.

**Comment by ljo** [comment]
So shall I open a PR for this then based on dev or v0.10?

**Comment by BobBorges** [comment]
@ninpnin how sure are you that renaming the protocol files doesn't break anything? I haven't looked into it yet.

**Comment by ninpnin** [comment]
The only thing I think we use the names for, is the infer_metadata function which detects the chamber, the year and the protocol number from the protocol ID. But I think the implementation would not break even if we add a couple of leading zeros.

**Comment by MansMeg** [comment]
@ljo I think opening up a PR based on dev is the best. Right @BobBorges and @ninpnin?

**Comment by BobBorges** [comment]
yep, branch off dev and open pr into dev

**Comment by fredrik1984** [comment]
@MansMeg @BobBorges – is this issue done too?

**Comment by MansMeg** [comment]
Yes!
