### ISSUE TITLE
Is the list of MPs (corpus/members_of_parliament.csv) outdated?

### ISSUE THREAD

**Issue by roger-mahler** [welfare-state-analytics/riksdagen-corpus#104]
Hello, and thanks for v0.3.0 of the riksprot corpus! 

I have run in to some trouble when trying to link the v0.3.0 corpus speech data to the CSV metadata. If I'm not mistaken, I believe the MOP file *members_of_parliament.csv* might be outdated, it's two months old in the v0.3.0 tag, and there are a lot of *who* attributes in the v0.3.0 corpus data that don't exist in the metadata. 

Out of 10 573 unique *who* ids in the v0.3.0 protocols; 9 378 are found in the metadata (8 705 in *members_of_parliament*, 591 in *ministers*, 82 in *speakers* and 0 in 'suppleants') whilst 1 195 ids are missing.

The missing ids exist in *members_of_parliament_sk*, but these are the only referenced ids in the corpus data, the 11 647 out of 12 841 don't exist in the v0.3.0 corpus.

Regards,
 Roger

**Comment by rbbby** [comment]
Hi, it sounds correct / as intended for this release, but that the data does not have the best structure at the moment (which we will work on in the near future). For clarity I will describe the way who-tags are made in the corpus:

1. Identify when a new speaker appears (and tag it as an intro)
2. Extract information about the speaker from the intro
3. If the person is identified as a talman or minister, match them against _talman_ or _ministers_ respectively
4. Else match them against _members_of_parliament_. If no match is found there, match them against _members_of_parliament_sk_. Since we match against _members_of_parliament_ first, we get most of the matches from there. 

_members_of_parliament_ and _members_of_parliament_sk_ contain data from the same original source (statskalendern) but has been gathered from wikipedia and OCR:ing the source material ourselves respectively. Both datasets has their benefits and issues respectively (different years/metadata missing, etc.) We would like to have a single file of all members but combining them has not been a priority for the 0.3 release.

Regarding _suppleants_ we have just recently gathered that data but not yet added it to be used in matching. But we will implement this as well as adding data for _replacers_ (suppleants replace for example ministers, but members of parliament can quit for other reasons and that data is gathered separately).

**Comment by roger-mahler** [comment]
Thank you for this clarification! I have adapted my logic according to your description. For the time beeing I'm creating a merged index of parliamentary persons in accordance to the following excel:

![image](https://user-images.githubusercontent.com/17061116/147067414-1f3d8dc2-6518-4712-a2a2-f959cacd2446.png)
