### ISSUE TITLE
Add statskalender and personregister data to our personregister

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#122]
Add persons, and members of parliament, from statskalendern and personregister to our personregister.

- [ ] Add source column in individuals.csv/persons.csv
- [ ] Add source column in members-of-parliament.csv
- [ ] Map individuals that is not in the wikidata to our files. 
- [ ] Send list with missing mps in wikidata to wd people

**Comment by salgo60** [comment]
@MansMeg please check how I add the sources to Sveriges statskalender 1877 in Wikidata --> you could extract the data with [SPARQL](https://w.wiki/4qdF) 

Would be great if you could reuse what I do and vice versa....

https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/36

**Comment by MansMeg** [comment]
This sounds good. We would like to sync so that we have the mps in statskalendern and personregisters in our mp file (ie in wikidata). Are you avout to do that?

**Comment by salgo60** [comment]
@MansMeg see https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/36 I guess Sveriges statskalender 1877 WD Q58366813 - [page 72-78](http://runeberg.org/statskal/1877/0096.html) is done (let me know if you find errors...)

* I prefer to use Runeberg as my reference so that we in our data can add the source with an URL to a page
  * Runeberg has the possibility to reference a page 
  * If we get persistent URLs to your data we can have also you as a source and even better create a **"welfare-state-analytics Wikidata property"**
     * my understanding of [Parla-Clarin](https://clarin-eric.github.io/parla-clarin/#sec-idents) is that the intention is to have a good link modell....  
     
 see also https://github.com/welfare-state-analytics/riksdagen-corpus/issues/108

**Comment by MansMeg** [comment]
Ok. I so not really follow. If Im correct (@rbbby knows) we have statskalendern and personregister with the mps over a large part of the 1900s. We would like to find the holes in wikidata based on this information and fill them.

How would we do that?

**Comment by MansMeg** [comment]
Fixed with the biobooks.
