### ISSUE TITLE
Duplicates in government.csv

### ISSUE THREAD

**Issue by TomasSkotare** [welfare-state-analytics/riksdagen-corpus#197]
There are several duplicates (identical rows) in the metadata file [government.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/dfb3eaa4535ddc341137de47c80d4b5c667166cb/corpus/metadata/government.csv)

This causes issues with later validation scripts, and it would be nice if those could be removed.

**Comment by MansMeg** [comment]
Could you do a PR with this edit? I guess it is quickly fixed.

**Comment by salgo60** [comment]
Here are the Wikidata Qnumbers if you would like to have **same as** in the file?

* [SPARQL list](https://w.wiki/5kf$) / [enWikipedia](https://w.wiki/5ka6) / [svWikipedia](https://w.wiki/5ka8)
 
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/14206509/192695721-af8f2c59-5d21-449f-9550-34edea512bb4.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/14206509/192695824-db29b129-9011-4ab6-b77c-7bbd425e399e.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/14206509/192695925-0d0da748-52b8-4f01-81e1-23c5dfd24716.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/14206509/192695982-6ecdf59e-08ad-4b32-997f-4ea62c844cd5.png">

**Comment by MansMeg** [comment]
That would be nice to have. Or what does @ninpnin think? Could you do a PR @salgo60 if Väinö gives a green light?

**Comment by ninpnin** [comment]
Sure, if the Qnumbers for the governments are nicely available, let's add them.

**Comment by salgo60** [comment]
I can try to do it tomorrow

@ninpnin 
a) name of WIkidata Q number column
b) shall we add sv [Wikipedia article name](https://w.wiki/5ka8) like:

[sv:Regeringen_Andersson](https://sv.wikipedia.org/wiki/Regeringen_Andersson) or the URL https://sv.wikipedia.org/wiki/Regeringen_Andersson

**Comment by ninpnin** [comment]
I think we should only add the wikidata q number column. The end user fetch the wikipedia article link themselves if necessary.

**Comment by ninpnin** [comment]
Also, the queary used to get the governments should be updated when we do this: https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/input/queries/government.rq

**Comment by MansMeg** [comment]
cool I open the issue again now

**Comment by salgo60** [comment]
A fix with Qnumber is done see [Pull 199](https://github.com/welfare-state-analytics/riksdagen-corpus/pull/199)
* (Maybe that list was generated with WD SPARQL and [should be fixed in the SPARQL](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/input/queries/government.rq)?)

**OT** 

@MansMeg can you call me about the POC #193  
Phone: 0735152802 
Its a suggestion how to integrate your data in a POC with Wikipedia would be a nice pattern for [ParlaMint](https://www.clarin.eu/parlamint)

I think its a approach to show. non believers about the power of #Linkeddata

**Duplicates in Riksdagens data**
We have spotted that Riksdagen has started to create 2 records for some newly added people. We have spoken with them and they are working on fixing it see [every-politician-scrapers/sweden-riksdag-api-current/issues/21](https://github.com/every-politician-scrapers/sweden-riksdag-api-current/issues/21)

**Comment by ninpnin** [comment]
Resolved
