### ISSUE TITLE
Add chair of MPs in as metadata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#228]
This needs to be done in collaboration with @JoeNoonan . I think we can start to discuss this issue here. What needs to be done? As I understood, @JoeNoonan has this property for some specific period. That would be a good starting point to add to get the structure right.

We also know that the chair is connected to an elected MP based on their role in the parliament. The question is how o store this information correctly. I guess it is a property in the member of parliament csv file, i.e when you are an active MP you have a chair. 

This information is also good for quality control of the active MPs in parliament.

**Comment by MansMeg** [comment]
So, now @JoeNoonan have extracted the matriklar going back to 1918 and all the way until (at least) the 90ties?

So we would like to add chair to the metadatabase. I suggest that we add it in the following way for now: 

As a csv called chair.csv with the following columns:
person_id, chamber, chair_number, date_from, date_to, reference

In reference I suggest we add the matrikel used so we can update wikidata with the chair data.

As I can see there are three tasks:
- [ ] add the matriklar data from Joe to the input folder (matriklar) - we probably want to use this for quality control of party as well
- [ ] create the chair.csv
- [ ] add a unit test that there is no empty chairs, noone sitting on two chairs or multiple people sitting at the same chair
- [ ] (after all unit tests update wikidata)

**Comment by JoeNoonan** [comment]
Here is the matriklar data from 1918-1970. These have missingness and OCR errors in them. But since we have a wide temporal coverage.  

[seats_1918_1960.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11746329/seats_1918_1960.csv)

This file has kammare, year, mp_description, seat_num, last_name, first_name, party, and birth_year

[seats_1961_1970.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11746352/seats_1961_1970.csv)

This file has kammare, year, raw_text, seat_num, name, and party

Here is the chair data from the scanned registers from 1971-1983:

There are six variables, rm, seat_num, last_name, first_name, party, ers, iort. ers is a flag if they are an ersättare. Party is missing for most of these. 

[seats_from_lists_1971_1983.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11746238/seats_from_lists_1971_1983.csv)

And lastly here is the chair data from the roll call votes (1983-1993): 

This has four variables. Riksmötets år, name, seat_num, party. There will be OCR errors in the names, but generally it shouldn't be too bad.

[unmatched_seats_from_rollcalls.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/11746299/unmatched_seats_from_rollcalls.csv)

**Comment by BobBorges** [comment]
Here are some preliminary results of working with the chair data. I'll try to lower some of these numbers when I can find sources. Interestingly, the 1960s (#325)  seems to be in pretty good shape

Duplicate chairs:* 1680
Missing chairs:** 2254
Empty chairs:*** 1858

\* Numbered chair listed twice in the same year/chamber. 
** Chair number not on the list, but should be, i.e. in [1,3,4,5], 2 is missing. The real number of missing chairs is not so dramatic -- there are three cases of a stray high number, chair 929, causing a lot of this.
*** Numbered chair appears in data with no MP filling it.

Summary semi-colon csv:
[completess-check.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/12051192/completess-check.csv)

**Comment by MansMeg** [comment]
Great news! I guess some of this might be easy to fix. I guess some errors can work in a first version that we might get some help from @JoeNoonan s project to fix. Do you open up a PR with this addition?

**Comment by JoeNoonan** [comment]
Great thanks! I'll take a look at this when I get back from vacation. I have the non-OCRed original pdfs for all of these years except for some years in the 1980s. I can share these when I get back to my computer.

**Comment by BobBorges** [comment]
> I can share these when I get back to my computer.

Thanks @JoeNoonan. That will be helpful.

**Comment by JoeNoonan** [comment]
Thanks so much for this @BobBorges. 

A few comments: 
- The "missing_chairs" column contains values outside of 1:349 for 197980 to 198283. I am not sure how to interpret this as there should be 1:350 seats from 1970 to 1975, then 1:349 from 1976 onwards
- The duplicate chairs aren't necessarily a problem after 1970 due to the ersättare system. But to check this we would need to do a unit test if the MP was an ersättare at the time where they had a duplicate seat or not. We don't have a flag for this in the mp database, but you could probably estimate whether it is an ersättare or not based on very short term periods for instance a month. 

[I have uploaded all of the PDFs to a Dropbox folder here.](https://www.dropbox.com/scl/fo/jmm978bv0vyqfrbrr2mjk/h?rlkey=ok00qp7h1fcvvm1x5w8picya6&dl=0) Some notes on these sources. For 1971 to 1993 the PDFs are scanned copies of "Förteckningar över Riksdagens ledamöter". These PDFs just contain the information we need. For the documents from 1961-1970, these are from the series REGISTER ÖVER RIKSDAGENS PROTOKOLL MED BIHANG RIKSDAGEN, which is available on the riksdagen.se. Here, the relevant information is in the second pdf "reg_02" and begins in the section with the header "Riksdagens ledamöter [YEAR]". This is usually on page 90-120. Lastly, The pre 1960s period, the seat data is in "reg_02" and begins with "Första kammarens ledamöter", in the section "MATRIKEL ÖVEK KAMRARNAS LEDAMÖTER" usually towards the end of the document. 

Lastly, on the correcting the errors. In terms of missing seats, would it be possible to interpolate the missing seats where we have some information, for instance, the seat the MP had the year before, and carry it over until the next election? From my understanding these seats should be fairly set from year to year between election periods. We can of course also do manual corrections and checks from our side as long as we know how to organize the data so it works with your work flow.

**Comment by BobBorges** [comment]
@JoeNoonan 
> The "missing_chairs" column contains values outside of 1:349 for 197980 to 198283. I am not sure how to interpret this as there should be 1:350 seats from 1970 to 1975, then 1:349 from 1976 onwards

These are from some error in the data, for example 1981-82 Hugo Bengtsson sits in chair 1353 according to the csv file I have. It means that the test I wrote thinks seat numbers 349-1352 are missing. So I can improve the test (check in range 1:349), and the data (where was Hugo, really). I've downloaded the sources you put on dropbox, so this will come soon.

> The duplicate chairs aren't necessarily a problem after 1970 due to the ersättare system....

This will also help us figuring out where mandate periods need attention. Good that you pointed this out, thanks!

> Lastly, on the correcting the errors. In terms of missing seats, would it be possible to interpolate the missing seats where we have some information, for instance, the seat the MP had the year before, and carry it over until the next election? From my understanding these seats should be fairly set from year to year between election periods. 

It's a reasonable strategy *if* the seats are indeed stable between elections. @fredrik1984 are you able to weigh in on this?

**Comment by fredrik1984** [comment]
Regarding Bob's question about MP-chair stability, I am not sure. @JoeNoonan ask Jan Teorell about this, he probably knows this better than me!

**Comment by JoeNoonan** [comment]
I'll shoot him an email now. @BobBorges, thanks for all of this, let us know if you want anyone from our side to make data corrections (like Hugo).

**Comment by BobBorges** [comment]
I'll rewrite the test to get a better idea of how prolific the problem actually is and get back to you.

**Comment by JoeNoonan** [comment]
I touched base with Jan on the interpolation. He wrote that he _thinks_ we can safely assume of stability of seats between elections, but that might be something we should just test beforehand with the data we have. He also pointed out that we cannot assume that the same person remains the entire election period sometimes MPs dropped out and replacements (before 1974 permanent ones) then assumed their seat.

**Comment by JoeNoonan** [comment]
We just did some checks on this. It won't work to interpolate. The seat position seems to be done also in part by seniority which means that replacements, or other changes, will cause shifts in the seat position.  We did some checks with the data that we have gathered filtering for only cases that had value for each year of the election cycle e.g. kiciking out the missing cases) and only 78% had a consistent seat number. Here is one example with Per Edvin Sköld, of movement around the seats:

**1933**
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/28146094/6951c925-4f4b-4ace-a237-0d76ef2aa811)

**1934**
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/28146094/8672cd19-244c-4562-b325-351efd3ac5c3)

**1935**
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/28146094/1ea7f386-36bd-482d-b9cb-0040b32c1e31)

This means we will have to go ahead manually fix the missing values, which our team can of course do.

**Comment by MansMeg** [comment]
So how do you store chair in the dataset now @BobBorges ? I guess we need to store it like this (where chair_id is unique):

```
chair_id,chair_no,person_id,date_from,date_to
```

Just so I get a feeling for how the data will be structured.

**Comment by BobBorges** [comment]
Right now it's still in the structure that I got it in, but I imagine sth similar to what you posted (though what's the difference between `chair_id` and `chair_no`?)

**Comment by MansMeg** [comment]
Great! 

Good question, that got me to think. The `chair_id` would be a unique id for each chair. I realize that we might want to have two files. One with information on the actual chair - I guess that would only be the chair number, chamber and maybe position (but that's super-low priority). Then we would have a `chair_mp_map.csv` file that would map the information on when an MP would sit in the specific chair. I think this would be a correct table formulation. So that would give two files:

`chair.csv`:
```
chair_id,chair_no,chamber
```
and `chair_mp_map.csv`:
```
chair_id,person_id,date_from,date_to
```

I guess this would be more clear?

**Comment by BobBorges** [comment]
I'm working on this issue now, and I'm still not sure if I understand why we would need a chair ID separate from the chair number. Do the chairs themselves get renumbered? Or we want to be able to track if a physical chair gets replaced, e.g. during renovations? It seems to me that chair IDs like f1, a1, e1 would be sufficiently indicative of an individual chamber/chair and its number. Is the chair + chair_mp_map not over complicating the data structure?

```
chair,person_id,start,end
a12,Q000001,19480101,19490101
f12,Q000002,19480101,19490101
e12,Q000003,20030101,20040101
```

**Comment by BobBorges** [comment]
Also, source material has only "Parliament year", no explicit start/end dates -- shall we leave 'end' blank and assume the lack of an explicit end date corresponds to the 'regular' end of a mandate period?

**Comment by MansMeg** [comment]
Yes. In general, we should not have primary keys that contain information. This is a good habit in general when constructing tables. See here:
https://www.techrepublic.com/article/the-great-primary-key-debate/

I'm not sure there has not been any reordering or that there might have been changes during 150 years of the parliament, but I would not be surprised if that could come up and then we would have the infrastructure for it right away.  

The only con/cost would be memory, and here, that is cheap.

I think we need to fill in the blanks here. Otherwise, data integrity testing will become more difficult.

**Comment by BobBorges** [comment]
> The only con/cost would be memory, and here, that is cheap.

Ok. UUIDs for chair?

> I think we need to fill in the blanks here. Otherwise, data integrity testing will become more difficult.

Then I think we will need another metadata file to map start / end dates to the standard terms. It will be useful when we need to infer dates in other meta tables -- in the mandate periods, for example.

**Comment by MansMeg** [comment]
UUID is a little overkill. But it works and is consistent.

Yes. I agree. Although, I think that is a seperate issue. So I would go with this for now and file an issue to fix this later.

**Comment by BobBorges** [comment]
Open PR, closing as duplicate of #347
