### ISSUE TITLE
Look up MPs with more than 1 party in the bio books and see if these parties are added in wikidata

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/riksdagen-corpus#359]
This issue relates to #349 and #355 

It is difficult for us to check the coverage of MPs with more than 1 party on Wikidata. I have a suggestion for this, which requires some manual labor.

When @Lottabrorsson, Mattias, and I go through the bio books and check specific start/end dates for MPs in Wikidata, we should also look up MPs in Wikidata that have more than 1 party in the bio books. I did a test and went through the first 100 pages in bio book 2. Although quite many MPs have more than one party, I was happily surprised that almost all MPs that I looked up had all parties listed on their Wikidata page.

Hence, if we don't feel that it is too much, we can both check specific start/end dates AND multiple party affiliations. We can make a list of each MP wikidata page that misses more than one party and we can fix this later (most likely we need to add reference to the bio books too).

- [x] Bio book 1 (Fredrik)
- [x] Bio book 2 (Fredrik)
- [x] Bio book 3 (Mattias)
- [x] Bio book 4 (Mattias)
- [x] Bio book 5 (Lotta)

**Comment by fredrik1984** [comment]
I have now gone through bio book 1–2 and checked all MPs that had more than one party affiliation stated in the books and checked if these parties are also listed on Wikidata including start/end year for party affiliation. 

Overall, I am very impressed and happy about the work that Wikidata (Magnus) has put into this! In total, I found 62 MPs that had at least one missing party or start/end party year. I was wondering if @salgo60 would like to go through these and add missing parties and proper references to the bio books? Below is a check list of MPs with missing parties with bio book reference.
 
- [ ] https://www.wikidata.org/wiki/Q5568434	vol. 1 s 55	
- [ ] https://www.wikidata.org/wiki/Q111692454	vol. 1 s 63	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q5732483	vol. 1 s 85 	start/end are missing for some parties in the bio book 
- [ ] https://www.wikidata.org/wiki/Q5776520	vol. 1 s 92	lmp misses start/end in the bio book
- [ ] https://www.wikidata.org/wiki/Q5795712	vol. 1 s 102 	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q1347810	vol. 1 s 119 	k party is missing
- [ ] https://www.wikidata.org/wiki/Q5359589	vol. 1 s 124	1 party missing
- [ ] https://www.wikidata.org/wiki/Q6020574	vol. 1 s 153 	should only be 1 prot party 1891-1909
- [ ] https://www.wikidata.org/wiki/Q6175996	vol. 1 s 170	1 party missing start/end
- [ ] https://www.wikidata.org/wiki/Q6178909	vol. 1 s 170	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q5901315	vol. 1 s 243	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q6147346	vol. 1 s 247	party + start/end missing
- [ ] https://www.wikidata.org/wiki/Q4723287	vol. 1 s 262	party + start/end missing
- [ ] https://www.wikidata.org/wiki/Q6233448	vol. 1 s 275	
- [ ] https://www.wikidata.org/wiki/Q1959642	vol. 1 s 313	
- [ ] https://www.wikidata.org/wiki/Q6147346	vol. 1 s 318	
- [ ] https://www.wikidata.org/wiki/Q5939069	vol. 1 s 319	
- [ ] https://www.wikidata.org/wiki/Q5973416	vol. 1 s 323	
- [ ] https://www.wikidata.org/wiki/Q5945227	vol. 1 s 380	party (prot) is missing
- [ ] https://www.wikidata.org/wiki/Q6010583	vol. 1 s 385	
- [ ] https://www.wikidata.org/wiki/Q5718511	vol. 1 s 432	
- [ ] https://www.wikidata.org/wiki/Q5795740	vol. 1 s 436	1 party missing start/end
- [ ] https://www.wikidata.org/wiki/Q5810543	vol. 1 s 437	
- [ ] https://www.wikidata.org/wiki/Q5828321	vol. 1 s 438	1 party missing
- [ ] https://www.wikidata.org/wiki/Q6192949	vol. 1 s 455	1 party missing start/end
- [ ] https://www.wikidata.org/wiki/Q6230364	vol 1. s 460	
- [ ] https://www.wikidata.org/wiki/Q6237662	vol. 1 s 460	
- [ ] https://www.wikidata.org/wiki/Q5568216	vol 2 s 50	
- [ ] https://www.wikidata.org/wiki/Q5786852	vol 2 s 72	
- [ ] https://www.wikidata.org/wiki/Q6085150		
- [ ] https://www.wikidata.org/wiki/Q5885736		
- [ ] https://www.wikidata.org/wiki/Q5984633	vol. 2 s 171	
- [ ] https://www.wikidata.org/wiki/Q6083558	vol. 2 s 180	
- [ ] https://www.wikidata.org/wiki/Q6167502	vol. 2 s 181	
- [ ] https://www.wikidata.org/wiki/Q6186078	vol. 2 s 185	
- [ ] https://www.wikidata.org/wiki/Q6198510	vol. 2 s 187	
- [ ] https://www.wikidata.org/wiki/Q5577789	vol. 2 s 207 --> this one has no start/end year for one of his parties in the bio book…	
- [ ] https://www.wikidata.org/wiki/Q6022797	vol. 2 s 227	
- [ ] https://www.wikidata.org/wiki/Q105037888	vol. 2 s 243	
- [ ] https://www.wikidata.org/wiki/Q5553493	vol. 2 s 259	
- [ ] https://www.wikidata.org/wiki/Q5571772	vol. 2 s 262	
- [ ] https://www.wikidata.org/wiki/Q5580347	vol. 2 s 264	
- [ ] https://www.wikidata.org/wiki/Q5603236	vol. 2 s 266	
- [ ] https://www.wikidata.org/wiki/Q5757453	vol. 2 s74 – enligt bion har han inte varit vilde, vilket han anges vara på wikidata	
- [ ] https://www.wikidata.org/wiki/Q5816360	vol. 2 s 280	
- [ ] https://www.wikidata.org/wiki/Q5973785	vol. 2 s 294	
- [ ] https://www.wikidata.org/wiki/Q5985507	vol. 2 s 296	
- [ ] https://www.wikidata.org/wiki/Q4723287	vol. 2 s 301 	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q6078330	vol. 2 s 306	
- [ ] https://www.wikidata.org/wiki/Q6083558	vol. 2 s 306	
- [ ] https://www.wikidata.org/wiki/Q5553493	vol. 2 s 331	
- [ ] https://www.wikidata.org/wiki/Q5580347	vol. 2. s 332	
- [ ] https://www.wikidata.org/wiki/Q5586815	vol. 2. s 333	Wrong party and others missing
- [ ] https://www.wikidata.org/wiki/Q5937903	vol. 2 s 340	
- [ ] https://www.wikidata.org/wiki/Q6017379	vol. 2 s 343	
- [ ] https://www.wikidata.org/wiki/Q6078330	vol. 2 s 344	
- [ ] https://www.wikidata.org/wiki/Q6083558	vol. 2 s 344	
- [ ] https://www.wikidata.org/wiki/Q6195597	vol 2. s 345	
- [ ] https://www.wikidata.org/wiki/Q5558134	vol. 2 s 369	Wrong party and others missing
- [ ] https://www.wikidata.org/wiki/Q5795712	vol. 2 s 381	start/end are missing
- [ ] https://www.wikidata.org/wiki/Q5806065	vol. 2 s 383 	start/end are missing (also in the bio book…)
- [ ] https://www.wikidata.org/wiki/Q6188940	vol. 2 s 400

**Comment by salgo60** [comment]
# Please call me so we are on the same page 0735152802?

* [ ] as long you dont deliver **persistent identifiers for Swedish parties** we cant do a good work in Wikidata
* [ ] you need to tell what parties mentioned in the book has what persistent identifier
* [ ] as said earlier I think we **need to share screens and I learn you how to change** and add sources using gadgets... 
   * this pattern that you look in the book and tell me to change is not serious - the approach I would like to see is that you have linked data, persistent identifiers, use sources and we can create Notebooks to see the diff in the [same way we do with Nobelprize.org](https://github.com/salgo60/NOSAD-POC-Wikidata/issues/13) - **we need to be more datadriven** and **Riksdagen corpus should be the source to Wikidata not vice versa**....
      * I have tried to tell you we miss the source Tvåkammar-riksdagen 1867–1970  [Q110346241](https://www.wikidata.org/wiki/Q110346241) on maybe 300 people see [list of candidates](https://w.wiki/7YdM) --> They have not been checked --> one person can take me an hour to add with birth/death records and grave and check the book.... [add pictures](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Salgo60&ilshowall=1)
      
      <img width="1354" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/9b6edebf-c9d1-4704-8731-4723a1744bed">    
        
      * **you are more productive** if you start adding sources when you check the books
 * [ ] get some feedback
     * [ ] we see no feedback on persistent identifiers and parties
     * [ ] we see no feedback were we have marked people with problematic parties [Välfärden analyserad - parti](https://www.wikidata.org/wiki/Q120143028) / Q120143028 - [324#issuecomment-1687925585](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/324#issuecomment-1687925585)
     
![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/445722ef-8fdd-4a22-8f50-0a7d05be6688)

**Comment by salgo60** [comment]
@fredrik1984 

Feedback [Q5568434](https://www.wikidata.org/wiki/Q5568434) - **project Riksdagens corpus needs to take the lead.....**

<img width="648" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/d59365a6-2b9d-4a27-a508-3f247aed79f4">

* you need to give us 
   * [ ] a Riksdagen corpus Persistent identifiers for "parties" and if possible same as Wikidata Qnumber
      * [ ] **stockholmsbänken** - WD [Q49098936](https://www.wikidata.org/wiki/Q49098936) I added my explanation "är en liberal gruppering i den svenska riksdagens andra kammare, som bildades år 1891 och upphörde 1892" - that I took from the WIkipedia article [Stockholmsbänken](https://sv.wikipedia.org/wiki/Stockholmsb%C3%A4nken) - is that correct... 
         * is this a party or what? below people connected to "**stockholmsbänken**"
             * Henrik Fredholm [Q5741552](https://www.wikidata.org/wiki/Q5741552) SPA [sj9PGLAlnmUAAAAAABfMlw](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfMlw) - 1891 - 1892
            * Adolf Hedin [Q4582704](https://www.wikidata.org/wiki/Q4582704) SPA [sj9PGLAlnmUAAAAAABfNnA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfNnA)
            * Sixten von Friesen [Q5744409](https://www.wikidata.org/wiki/Q5744409) SPA [sj9PGLAlnmUAAAAAABfMqQ)](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfMqQ)
            * .....
        * [ ] **centern** persistent identifier needed and also metadata if possible
           * followed by
           * inception, ended
           * instance of a political party?
           * .....
        * [ ] **lib s** I guess we know is [Q1594086](https://www.wikidata.org/wiki/Q1594086) but is the english translation ok that looks like its added by a bot called [BeneBot](https://www.wikidata.org/wiki/User:BeneBot*) ;-) 
        
<img width="910" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/61da3c48-ccba-48d8-ad76-45efdc1b2e53">

### Textstring search "Stockholmsbänken" in the book [Tvåkammar-riksdagen 1867–1970](https://www.wikidata.org/wiki/Q110346241)

Band 1
* sid 15
<img width="453" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/21becefe-64a0-4b5b-a4c6-7f80dbfe3f11">

* sid 33
<img width="453" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/5b877a46-f1a7-44cb-9323-b41f6067bf82">

* sid 34
<img width="453" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/4d2202e2-71c3-434b-9515-c3192392eb7a">

**Comment by fredrik1984** [comment]
Haha, yes, the 19th-century parties are a mess. But we should for now stick to what the bio books state. Hence, stockholmsbänken is a party. We need to start somewhere, one step at a time. I will discuss persistent party identifiers with the others in the Swerik project.

**Comment by salgo60** [comment]
## ok then you can add it to Wikidata  

**I dont feel confident add odd things like this**...
* [nya centern #358](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/358#issuecomment-1739573620)
* I also feel "centern" is not well defined see [157#issuecomment-1714283975](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/157#issuecomment-1714283975)

<img width="883" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/6e927885-6f40-4a9f-82b5-3a86a9ffcfaf">

<img width="723" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/0630b076-7bfd-4863-8750-8bf71a3ac93f">

**Comment by fredrik1984** [comment]
@BobBorges I have now completed 1) the list of MPs with no party at all in Wikidata, and 2) the list of MPs with more than one party in the bio books. 

In the two sheets I have added the necessary info that you will need to add missing parties to relevant MPs:

https://docs.google.com/spreadsheets/d/1bywraAUEoRy-XPNjfk-7rpMhnQKLJc1EvSQyP3S9GII/edit#gid=298081134

Let me know if you have any questions about this! 

Then we wait for Lotta and Mattias to complete their share of the work.

**Comment by salgo60** [comment]
@fredrik1984 looks odd with e.g. centern 

<img width="1316" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/6af7f340-209d-44ca-b94b-2d8ef3f937b8">

**Comment by fredrik1984** [comment]
Yes, in a way. But this is what this old "centern" was called in the 19th century according to the bio books. Note however that the present so-called center party is officially called "Centerpartiet" and not "centern".

**Comment by salgo60** [comment]
> Yes, in a way. But this is what this old "centern" was called in the 19th century according to the bio books. Note however that the present so-called center party is officially called "Centerpartiet" and not "centern".

The dates **start end** doesnt match the dates in field **full_party_name**

**Comment by fredrik1984** [comment]
Ah, that is actually weird! When I search for "centern" in the bio books, I find several MPs that belong to this party name but after the time period of "centern" (1873–1882). Hm, even the bible has its flaws, but we also know that it is a mess with the 19th century. I will create an issue about this. 

Thanks for spotting this @salgo60!

**Comment by salgo60** [comment]
> Hm, even the bible has its flaws

They used **1940 years technology** [strings not things](https://blog.google/products/search/introducing-knowledge-graph-things-not/) much more tragic that projects like [SKBL](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/358#issuecomment-1741679410)/SBL 2023 dont create knowledge graphs... a sad example is "[SBL släktartiklar](https://github.com/salgo60/Svenskaforsamlingar/issues/7)" that I now add to WIkidata see example [Laurell, släkter](https://commons.wikimedia.org/wiki/Category:Laurell,_sl%C3%A4kter)
* [fråga direkt till Riksarkivet SBL vid 46:10 min](https://www.youtube.com/watch?v=ywFsLrn43N0&t=2770s) att jobba med strukturerad data och inte textsträngar, dålig bortförklaring .... att dom på 100 år inte skapat rätt kompetens är sorgligt...

![image](https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/d63287bd-42ec-4f3d-9c91-543613d0915f)

* see Wikidata [#32 Kunna hantera motstridiga fakta och flerspråkighet](https://github.com/salgo60/SamlaLibris/issues/32) / [SBL #39](https://github.com/salgo60/Svenskaforsamlingar/issues/39)

**Comment by salgo60** [comment]
@BobBorges can you help us with English party names in Wikidata

* [Property dasboard for people i the second chamber grouped on parties](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Sweden/Coverage_by_party_second)

If you run it in English you see Qnumbers because lack of english names and also you see maybe a bad habit to use the Swedish name as the english name e.g. [Q111033682?uselang=en](https://www.wikidata.org/wiki/Q111033682?uselang=en)

Looks like [@MonirEliasBounadi](https://www.wikidata.org/wiki/Special:Contributions/MonirEliasBounadi) alias @monirbounadi has edit the english labels

<img width="1026" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/b675f6c9-0789-4db4-9a22-2ab11434094e">

----

<img width="1206" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/275d012c-0d56-4506-af53-e8e28e6df5a5">

<img width="1206" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/1cd4716e-11c4-410b-8afb-efc2877b5b98">

<img width="1206" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/dc839254-f5b1-444a-b716-de479c73369a">

<img width="1206" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/c862fe46-fb81-4246-a986-54bc7bed7b3a">

**Comment by salgo60** [comment]
## looks like we never will have a session learning you the basic of WIkidata 

### Less good EDITS I see

1. When you add source add them in the same way as the rest not invent new patterns 

**Reason**: When Wikipedia use templates and sources exists in many different forms you will get "duplicates in the article"

Eg. @BobBorges  added [Q6001723#2561](https://www.wikidata.org/wiki/Q6001723#2561)

<img width="982" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/a78d9656-43e7-46e7-92ac-eb92d2b58ce8">

Preferred format

<img width="988" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/d57e9dfc-3ddf-4236-9e18-f2a30a27d865">

2. create churchbook links to Riksarkivets free resources with a link

@monirbounadi added

<img width="982" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/e5a9c077-de14-44a5-830e-57cb2cf9fecb">

Preferred format

<img width="1069" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/52c345d9-cdc0-4aa3-aba1-195119c29e53">

**Comment by monirbounadi** [comment]
Thanks @salgo60! Regarding 2: I also prefer the other format you mention, but the first format is not incorrect and it takes less time for me as I use ArkivDigital. Also, I do not seem to have the function "kopiera" when I add references. How do I get that?

Regarding "Högerpartiet": Fixed!

**Comment by MansMeg** [comment]
I dont see anything wrong with @BobBorges update? Its just missing svenskt porträttarkiv and the registry entry? But we dont use that so we cannot update that unless its done manually, and that is not a priority for us.

**Comment by BobBorges** [comment]
@salgo60 Could you point out exactly what your issue is with my edit? It's not clear from the screenshots what new pattern I have invented. I'm happy to take constructive criticism and learn from mistakes, but I don't appreciate the above style of feedback. If you really feel that we're lacking fundamental / basic understanding of how to add info to wikidata, let's organize a workshop.

**Comment by salgo60** [comment]
@BobBorges i have told you 100 times to show you Wikidata that is very frustrating... and that we dont get persistant identifiers from you is also frustrating,,,

As you are the consumer of the data I feel you should care more and follow best practice...

### Why adding sources in the same way is best practice...

svWikipedia [Johannes Mörtsell](https://sv.wikipedia.org/wiki/Johannes_M%C3%B6rtsell)

<img width="1218" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/f0ba1cd7-4a67-4c1f-8854-47c2f54ab990">


> I dont see anything wrong with @BobBorges update? Its just missing svenskt porträttarkiv and the registry entry? But we dont use that so we cannot update that unless its done manually, and that is not a priority for us.

As we use [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and templates see [Mall:Faktamall_biografi_WD](https://sv.wikipedia.org/wiki/Mall:Faktamall_biografi_WD)

The problem is that if if we add "the same" reference in different ways the sources will be presented as more references in the article see screen shoot above where...  As Wikidata **is used by 300 Wikipedia languages** its even more important that what is added to Wikidata is as good as possible

1. is the way I think you should add references to the book with the SPA book clickable
2. is the result when you dont follow the "same" pattern.... --> we get another reference

**In wikidata we have gadgets for doing this more easy** see my post "[#123 Wikidata gadgets good to use](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/123)"

>>> we dont use that so we cannot update that unless its done manually
you can read it from WIkidata P1343

* e.g. [Q6001723#P1343](https://www.wikidata.org/wiki/Q6001723#P1343)

<img width="939" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/95199ad2-c064-41aa-8c39-f3b50ae05eaa">

----
# adding church books references just as a **text string**
By adding the churchbook ref with more structured data you get added value
* [NAD P5324](https://www.wikidata.org/wiki/Property:P5324) --> we get information of the book location
* [page P304](https://www.wikidata.org/wiki/Property:P304) 
* [referens‐URL](https://www.wikidata.org/wiki/Property:P854)--> **in the article we get a clickable link** and the reader can check the facts

As we also have different systems like SVAR and [Arkiv Digital](https://www.arkivdigital.se/) and many church book lacks page number its everyday in the week **1000 times better to point on the digital representation** and as we have **free churchbooks from Riksarkivet that is the best practice**...

#### 2023 we need to leave the way Riksarkivet SBL works 2023... they works as they did in 1917 

I asked SBL 2023 why they after 100 years of producing SBL cant produce some structured data they answered it was a wish [my direct question at 46:00 ](https://youtu.be/ywFsLrn43N0?si=djqELCaO-NKhorLf&t=2758) if they cant produce better Digital data today its just text strings and no links to other historical documents... and no API....

<img width="939" alt="image" src="https://github.com/welfare-state-analytics/riksdagen-corpus/assets/14206509/db6bfc40-f2d5-48fb-b86a-70e51196b37e">

**Comment by BobBorges** [comment]
@salgo60 It is also frustrating to be criticized and not understand what you're being criticized about. 

From your commentary, I understand that you think I added the bio book source in the wrong way, and I completely agree that adding sources to make duplicates is wrong, but you don't say what about my edit is wrong in such a way that I can fix it. 

DRY is good, we're on the same page with that. But posting a wall of aggressive text without pointing out the actual problem doesn't address the issue. 

>100 times to show you Wikidata that is very frustrating... 

I've made a few batch edits in early summer, and only one or two by hand since then. I haven't been working with this much, hence no contact with you about doing thing better. Let's cut out the insinuations and make a feasible plan to improve cooperation. Shall we organize some kind of afternoon workshop where you can give a walk through of best practices working with wikidata?

**Comment by salgo60** [comment]
> @salgo60 It is also frustrating to be criticized and not understand what you're being criticized about.
> 
And that is the reason we need to share screen 5 minutes

> DRY is good

It could be better right now we dupiicate everthing **which is** bad but I see no better way... my priority has been to get it good looking in the articles... and then the template construction wirks with duplicates....

> Shall we organize some kind of afternoon workshop where you can give a walk through of best practices working with wikidata?


* [Share screen link](https://meet.jit.si/Wikidata-SV)

 feel its better we do more and shorter sharing a screen is the best and I dont have all answers you can ask on [Telegram](https://t.me/joinchat/SPlRqI5xcw7ugXlE) and on a [WD chat](https://www.wikidata.org/wiki/Wikidata:Project_chat)
 
 1. issues I would like to see that we are on the same page or agree that we disagree
 1-1) The importance of Persistent Identifiers for all parties i.e. [not doing what SKBL did again](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/358#issuecomment-1741679410)
 1-2) Status of getting persistent identifiers from you is it in the pipline
2. **I also feel Wikidata should not be the master** --> you should be the master for most different objects like below what is your plan
2-1) parties
2-2) people
2-3) positions like [Q81531912](https://www.wikidata.org/wiki/Q81531912)
2-4) and guess **many more objects do you have a plan**
 
 I have a screen sharing on [link meet.jit.si/Wikidata-SV](https://meet.jit.si/Wikidata-SV)

**Comment by BobBorges** [comment]
> feel its better we do more and shorter sharing a screen is the best and I dont have all answers you can ask on [Telegram](https://t.me/joinchat/SPlRqI5xcw7ugXlE) and on a [WD chat](https://www.wikidata.org/wiki/Wikidata:Project_chat)
> I have a screen sharing on [link meet.jit.si/Wikidata-SV](https://meet.jit.si/Wikidata-SV)

I am working with completely other things today, and this week in general, so I think a meeting right now would not be very productive because my mind is elsewhere, but I do have a pile of info to add to wikidata. Can we talk/share screens in a week or so? Then I will be more attentive to the data in front of me and probably asking more pertinent questions.

**Comment by salgo60** [comment]
let me know when its ok for you and **as said its more in your interest that the data data will be good that its for me...**

* my plan is to do [250 more wikidata profiles who lack referencies](https://w.wiki/7hyg) and then over and out from caring about Wikidata and Swedish PM people.... I hope my last Wikidata edit will be this year after [90 months editing](https://wikidata.wikiscan.org/user/Salgo60)

**Comment by fredrik1984** [comment]
relates to #235
