### ISSUE TITLE
Add Twitter information on individual MPs as meta-data

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#43]
http://makthavare.se/2018/09/19/kartlaggning-har-ar-riksdagsledamoterna-pa-twitter-2/

**Comment by MansMeg** [comment]
https://github.com/peterdalle/swedishtwitter

**Comment by fellennert** [comment]
I'm currently joining together the two lists (i.e., the one from the Git repository and the member meta-data one). One thing that bothers me is that party names change over the years. For instance, from 2006--2010 it's "Miljöpartiet de Gröna" and thereafter it's "Miljöpartiet de gröna" (lowercase g), 2014 it becomes Miljöpartiet. For joining the tables together, this is tedious. I can imagine that it also bears potential for errors when filtering (since you would have to do something like 

`filter(party %in% c("Miljöpartiet de Gröna", "Miljöpartiet de gröna", "Miljöpartiet"))`

). Would it make sense to add another column with just the party abbreviation for

`filter(party == "MP")` 

(just an example)? If so, I can fix that right away for the "current" parties from which I know the abbreviation. I have to do it anyways to join the tables properly.

**Comment by MansMeg** [comment]
I think it sounds like a good idea. What do @ninpnin say?

**Comment by ninpnin** [comment]
We have already done the same thing for other parties. I think the work should be finalized

**Comment by ninpnin** [comment]
Though we use harmonized versions of the full names (Miljöpartiet de gröna, Miljöpartiet -> Miljöpartiet) now?

**Comment by MansMeg** [comment]
? Sorry, I dont understand.

**Comment by fellennert** [comment]
I fixed it now with the abbreviations @Stubbendorff suggested. See discussion in #47 .

**Comment by ninpnin** [comment]
Done.

**Comment by MansMeg** [comment]
Cool! Is this done? Where is that data?

**Comment by ninpnin** [comment]
At least we merged this at some point?

**Comment by MansMeg** [comment]
? But where is the twitter data then?

**Comment by ninpnin** [comment]
There is a column for the twitter handles and apparently 1 value ?

**Comment by MansMeg** [comment]
In what file? The MOP file?

**Comment by ninpnin** [comment]
https://raw.githubusercontent.com/welfare-state-analytics/riksdagen-corpus/dev/corpus/members_of_parliament.csv

**Comment by MansMeg** [comment]
Ah yes. This remind me that we should formulate the mop data into at least the third normal form for databases. Ill file this as an issue.
